apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: client
      app.kubernetes.io/instance: client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: client
        app.kubernetes.io/instance: client
    spec:
      containers:
        - name: client
          image: smoreno/simpleclient:latest
          imagePullPolicy: IfNotPresent
          # ports:
          #   - name: http
          #     containerPort: 8080
          #     protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080

