apiVersion: v2
name: prometheus-grafana
description: A Helm chart for Prometheus Grafana
version: 1.0.0
appVersion: 1.0.0
home: https://prometheus.io/
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
dependencies:
- name: grafana
  version: 1.2.9
  repository: https://charts.bitnami.com/bitnami
  condition: grafana.enabled
- name: prometheus
  version: 11.0.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: prometheus.enabled