# Configuration for Prometheus Grafana stack
grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30002
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-prometheus-server
          access: proxy
          isDefault: true

prometheus:
  enabled: true