apiVersion: v1
kind: Service
metadata:
  name: provider
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: provider
    app.kubernetes.io/instance: provider
