kind: Secret
apiVersion: v1
metadata:
  name: demo-es-user-secret
  namespace: elastic
type: kubernetes.io/basic-auth
stringData:
  username: admin    # required field for kubernetes.io/basic-auth
  password: admin123 # required field for kubernetes.io/basic-auth
  roles: superuser,kibana_admin,ingest_admin  # optional, not part of kubernetes.io/basic-auth